
project_id = "epitbbwnyikpazjtptnw"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.increment-playlist-count]
verify_jwt = true

[functions.process-music-request]
verify_jwt = true
