// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epitbbwnyikpazjtptnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwaXRiYndueWlrcGF6anRwdG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzA2MjksImV4cCI6MjA2MDQ0NjYyOX0.u1jCnoaWFfOXUWtQNZ15SY47z5Te0ZUuHOQdnuncbj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);